# web服务端口号
server.port: 8080
management:
  endpoints:
    web:
      base-path: /monitor
      path-mapping:
        health: /alive

spring:
  profiles:
    active: @active-profile@

#日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-online.xml

# Zebra属性配置
zebra:
  jdbcRef: mtchi_base_xframe_dev # jdbcRef配置, 通过profile隔离
  poolType: druid
  minPoolSize: 5
  maxPoolSize: 30
  initialPoolSize: 5
  checkoutTimeout: 1000
  maxIdleTime: 1800
  idleConnectionTestPeriod: 60
  sqlSessionFactory:
    typeAliasesPackage: com.meituan.mzt.domain
    plugins:
      - className: com.github.pagehelper.PageInterceptor
        properties:
          helperDialect: mysql # 数据库方言配置，默认为mysql。当使用其他数据库时请对应修改，例如：PostgreSQL数据库配置为postgresql、DB2数据配置db2等。
  zebraMapperScannerConfigurer:
    basePackage: com.meituan.mzt.mapper


# Squirrel属性配置
#squirrel:
#  clusterName:  # 必填，集群名称

# Mafka属性配置
#mafka:
#   producer: # 生产者配置
#     namespace: # 必填，所属业务
#     topic: # 必填，消息主题
#   consumer: # 消费者配置
#     namespace: # 必填，所属业务
#     topic: # 必填，消息主题
#     group: # 必填，消费组名称
#     listener: # 必填，监听器类全路径
#     className: # 必填，发送消息类型，用于解码

---

spring:
  profiles: local

#日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-local.xml
  level.com.meituan.mzt.mapper: debug # 打印mybatis的sql日志

---

spring:
  profiles: dev

#日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-offline.xml
zebra:
  jdbcRef: mtchi_base_xframe_dev #替换为自己dev环境的jdbcRef

---

spring:
  profiles: test

#日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-offline.xml
zebra:
  jdbcRef: mtchi_base_xframe_test #替换为自己test环境的jdbcRef


# Squirrel属性配置
#squirrel:
#  clusterName:  # 必填，集群名称

---

spring:
  profiles: staging

zebra:
  jdbcRef: mtchi_base_xframe #替换为自己staging环境的jdbcRef


# Squirrel属性配置
#squirrel:
#  clusterName:  # 必填，集群名称

---

spring:
  profiles: prod

zebra:
  jdbcRef: mtchi_base_xframe #替换为自己prod环境的jdbcRef


# Squirrel属性配置
#squirrel:
#  clusterName:  # 必填，集群名称
